image: atlassian/default-image:4
pipelines:
  branches:
    #for ebextensions branch  just echo  
    '{ebextensions}':
      - step:
          name: "Echo for ebextensions branch"
          script:
            # Simple echo for this branch 
            - echo "This is the ebextensions branch"
    '{dev}':
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            #- npm run test
          services:
            #- mongo
            - docker
          artifacts:
            - '**/*' 
      - step:
          name: "Adjust configs and package for dev  branch"
          script:
              # Clone the 'ebextensions' branch from the main repository
              # to the '/tmp/ebextensions' directory in the pipeline environment
              #- git clone -b ebextensions git@bitbucket.org:socialmoney/newco.git /tmp/ebextensions
                # List all the files in the '/tmp/ebextensions' directory to check if files were cloned successfully
              ##- ls -lah /tmp/ebextensions
                # Get the name of the current git branch and store it in the 'BRANCH' variable
              #- BRANCH="$(git rev-parse --abbrev-ref HEAD)"
                # Overwrite or add the branch-specific '.ebextensions' files from the cloned repository
              # to the '.ebextensions' directory in the current repository
              #- cp -af "/tmp/ebextensions/.ebextensions.$BRANCH/." .ebextensions/
              #  Create a zip file of the current repository, excluding specified directories
              - zip -r -9 application.zip . -x .git/**\* -x blog/**\* -x localhost.sql -x vendor/**\*
                 #       Define the 'application.zip' file as an artifact that should be stored after the build
          artifacts:
            - application.zip
      - step:
          name: "Deploy to dev"
          trigger: manual
          deployment: customer-portal-dev
          script:
            - BRANCH_NAME_CLEAN=$(git rev-parse --abbrev-ref HEAD | sed -r 's/[\.]/-/g')
            - pipe: atlassian/aws-elasticbeanstalk-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: "eu-west-1"
                APPLICATION_NAME: "payl8r-customer-portal"
                ENVIRONMENT_NAME: "Payl8r-customer-portal-env-DEV"
                ZIP_FILE: "application.zip"
                S3_BUCKET: "elasticbeanstalk-payl8r-bucket"
                DEBUG: "false"
                WAIT: "true"
                WAIT_INTERVAL: '10'
                WARMUP_INTERVAL: '0'
                VERSION_LABEL: 'deploy-$BITBUCKET_BUILD_NUMBER-payl8r-customer-portal-env'
#definitions:
#  services:
#    mongo:
#      image: mongo 
